#! /usr/bin/env atf-sh

SERVER_HOST=localhost
SERVER_PORT=2345
SERVER=${SERVER_HOST}:${SERVER_PORT}

PROXY_HOST=localhost
PROXY_PORT=5432
PROXY=${PROXY_HOST}:${PROXY_PORT}

base_head() {
    atf_set "require.progs" "diff nc proxy"
    atf_set "descr" ${1:-"A given request produces the expected" \
                         "request at the server when proxied"}
}
base_body() {
    nc -l ${SERVER_PORT} > test.out &
    proxy -v ${PROXY_PORT} &
    nc ${PROXY_HOST} ${PROXY_PORT} < test.in
    diff -u test.ok test.out
}

atf_test_case request1
request1_head() {
    base_head "The proxy removes the Proxy-Connection header from" \
              "the request"
}
request1_body() {
    echo -e "GET http://${SERVER}/ HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
" > test.in

    echo -e "GET / HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
" > test.ok

    base_body
}

atf_test_case request2
request2_head() {
    base_head "The proxy requests the correct path+query+fragment" \
              "from the server"
}
request2_body() {
    local path query fragment
    path="/hello"
    query="?p=q&s=t;f"
    fragment="#xyz"
    echo -e "GET http://${SERVER}${path}${query}${fragment} HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
" > test.in

    echo -e "GET ${path}${query}${fragment} HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
" > test.ok

    base_body
}

atf_test_case request3
request3_head() {
    base_head "The proxy rejects an empty path"
}
request3_body() {
    echo -e "GET http://${SERVER} HTTP/1.0\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
" > test.in

    echo -n > test.ok

    base_body
}

atf_init_test_cases() {
    atf_add_test_case request1
    atf_add_test_case request2
    atf_add_test_case request3
}

# Local Variables:
# mode: sh
# End:
# vim: filetype=sh fileformat=unix
