#! /usr/bin/env atf-sh

SERVER_HOST=localhost
SERVER_PORT=2345
SERVER=${SERVER_HOST}:${SERVER_PORT}

PROXY_HOST=localhost
PROXY_PORT=5432
PROXY=${PROXY_HOST}:${PROXY_PORT}

dummy_request() {
    echo -e "GET http://${SERVER}/ HTTP/1.0\r\nHost: ${SERVER}\r\n\r\n"
}
base_head() {
    atf_set "require.progs" "nc proxy"
    atf_set "descr" ${1:-"A given response produces the expected" \
                         "response at the server when proxied"}
}
base_body() {
    nc -l ${SERVER_PORT} < test.in &
    proxy -v ${PROXY_PORT} &
    dummy_request | nc ${PROXY_HOST} ${PROXY_PORT} > test.out
    diff -u test.ok test.out
}

atf_test_case response1
response1_head() {
    base_head "The proxy responds with the server's full response"
}
response1_body() {
    echo -e "\
HTTP/1.1 404 Not Found\r
Date: Sat, 21 Apr 2018 02:24:10 GMT\r
Server: Apache/2.4.18 (Fedora) OpenSSL/1.0.1k-fips\r
Content-Length: 208\r
Content-Type: text/html; charset=iso-8859-1\r
\r
<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /index.html was not found on this server.</p>
</body></html>
" > test.in

    cp test.in test.ok

    base_body
}

atf_init_test_cases() {
    atf_add_test_case response1
}

# Local Variables:
# mode: sh
# End:
# vim: filetype=sh fileformat=unix
