#! /bin/sh


#	So Far wokring as intended
#changed all the capital letters of the command to lowercase


# use this in vim if not working ->    :set fileformat=unix
 TESTNO=${1}  # use TESTNO to select a test case

SERVER_PORT=12345
PROXY_PORT=54321

run_proxy() {
	# ./proxy ${1}
	nc -l ${1} | sed -e "s#GET http://localhost:${SERVER_PORT}#GET #" -e "/proxy-connection/d"| nc localhost ${SERVER_PORT}
}

echo -e "GET http://localhost:${SERVER_PORT}/ HTTP/1.1\r
host: localhost:${SERVER_PORT}\r
user-agent: curl/7.54.0\r
accept: */*\r
proxy-connection: keep-alive\r
\r
" > test.in

echo -e "GET / HTTP/1.1\r
host: localhost:${SERVER_PORT}\r
user-agent: curl/7.54.0\r
accept: */*\r
\r
" > test.ok

echo "Running server"
nc -l ${SERVER_PORT} > tmp.out &

echo "Running proxy"
run_proxy ${PROXY_PORT} &

echo "Running client"
#nc localhost ${PROXY_PORT} < test.in
nc localhost ${PROXY_PORT} < test${TESTNO}.in

# cleanup
# rm tmp.out
kill %1
kill %2

diff -u tmp.out test.ok
