#! /usr/bin/env atf-sh

atf_test_case hflag
hflag_head() {
    atf_set "require.progs" "proxy"
    atf_set "descr" "The -h flag shows a help message"
}
hflag_body() {
    atf_check -o match:usage proxy -h
}

atf_init_test_cases() {
    atf_add_test_case hflag
}

# Local Variables:
# mode: sh
# End:
# vim: filetype=sh fileformat=unix
