#! /usr/bin/env atf-sh

SERVER_HOST=localhost
SERVER_PORT=2345
SERVER=${SERVER_HOST}:${SERVER_PORT}

PROXY_HOST=localhost
PROXY_PORT=5432
PROXY=${PROXY_HOST}:${PROXY_PORT}

base_head() {
    atf_set "require.progs" "diff hexdump nc printf proxy"
    atf_set "descr" ${1:-"A given request produces the expected" \
                         "request at the server when proxied"}
}
base_body() {
    nc -l ${SERVER_PORT} > test.out &
    proxy -v ${PROXY_PORT} &
    nc ${PROXY_HOST} ${PROXY_PORT} < test.in

    echo "expected request:"
    hexdump -C test.ok
    echo "actual request:"
    hexdump -C test.out

    diff -u test.ok test.out \
        || atf_fail "Actual request did not match expected"
}

atf_test_case request1
request1_head() {
    base_head "The proxy removes the Proxy-Connection header"
}
request1_body() {
    printf > test.in "\
GET http://${SERVER}/ HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
"
    printf > test.ok "\
GET / HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    base_body
}

atf_test_case request2
request2_head() {
    base_head "The proxy requests the correct path+query+fragment"
}
request2_body() {
    local path query fragment
    path="/hello"
    query="?p=q&s=t;f"
    fragment="#xyz"
    printf > test.in "\
GET http://${SERVER}${path}${query}${fragment} HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
"
    printf > test.ok "\
GET ${path}${query}${fragment} HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    base_body
}

atf_test_case request3
request3_head() {
    base_head "The proxy rejects an empty path"
}
request3_body() {
    printf > test.in "\
GET http://${SERVER} HTTP/1.0\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    echo -n > test.ok
    base_body
}

atf_test_case request4
request4_head() {
    base_head "The proxy removes the Proxy-Connection header from middle"
}
request4_body() {
    printf > test.in "\
GET http://${SERVER}/ HTTP/1.1\r
Host: ${SERVER}\r
Proxy-Connection: Keep-Alive\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    printf > test.ok "\
GET / HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    base_body
}

atf_test_case request5
request5_head() {
    base_head "The proxy removes the Proxy-Connection header from first"
}
request5_body() {
    printf > test.in "\
GET http://${SERVER}/ HTTP/1.1\r
Proxy-Connection: Keep-Alive\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    printf > test.ok "\
GET / HTTP/1.1\r
Host: ${SERVER}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"
    base_body
}

atf_test_case request6
request6_head() {
    atf_set "require.progs" "dd diff hexdump nc printf proxy sed"
    atf_set "descr" "Large request body"
}
request6_body() {
    local content_length
    content_length=64000000 # 64MB > 2*8000 (size of request buffer)
    printf > test.in "\
POST http://${SERVER}/upload HTTP/1.0\r
Host: ${SERVER}\r
Content-Type: application/octet-stream\r
Content-Length: ${content_length}\r
\r
"
    dd if=/dev/zero bs=${content_length} count=1 >> test.in
    sed "s#http://${SERVER}##" test.in > test.ok
    base_body
}

atf_init_test_cases() {
    atf_add_test_case request1
    atf_add_test_case request2
    atf_add_test_case request3
    atf_add_test_case request4
    atf_add_test_case request5
    atf_add_test_case request6
}

# Local Variables:
# mode: sh
# End:
# vim: filetype=sh fileformat=unix
