#! /bin/sh


#	So Far wokring as intended


# use this in vim if not working ->    :set fileformat=unix

SERVER_PORT=2345
PROXY_PORT=5432

echo -e "GET http://localhost:${SERVER_PORT}/ HTTP/1.1\r
Host: localhost:${SERVER_PORT}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
" > test.in

echo -e "GET / HTTP/1.1\r
Host: localhost:${SERVER_PORT}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
" > test.ok

echo "Running server"
nc -l ${SERVER_PORT} > tmp.out &

echo "Running proxy"
proxy -v ${PROXY_PORT} &

echo "Running client"
nc localhost ${PROXY_PORT} < test.in

echo "Cleaning up"
kill %1 && wait %1
kill %2 && wait %2

echo "Results"
diff -u test.ok tmp.out
