#! /bin/sh


#	Works on diffrent ports All is good


# use this in vim if not working ->    :set fileformat=unix

SERVER_PORT=12335 		#modified
PROXY_PORT=54321

printf > test.in "\
GET http://localhost:${SERVER_PORT}/ HTTP/1.1\r
Host: localhost:${SERVER_PORT}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
Proxy-Connection: Keep-Alive\r
\r
"

printf > test.ok "\
GET / HTTP/1.1\r
Host: localhost:${SERVER_PORT}\r
User-Agent: curl/7.54.0\r
Accept: */*\r
\r
"

echo "Running server"
nc -l ${SERVER_PORT} > test.out &

echo "Running proxy"
proxy -v ${PROXY_PORT} &

echo "Running client"
nc localhost ${PROXY_PORT} < test.in

echo "Cleaning up"
kill %1 && wait %1
kill %2 && wait %2

echo "Results"

echo "expected request:"
hexdump -C test.ok
echo "actual request:"
hexdump -C test.out

diff -u test.ok test.out
