#! /bin/sh


#	So far working as intended




# use this in vim if not working ->    :set fileformat=unix
 TESTNO=${1}  # use TESTNO to select a test case

SERVER_PORT=3128
PROXY_PORT=3333

echo -e "GET http://blue.cs.sonoma.edu:3333/page_name.html HTTP/1.0\r
Host: blue.cs.sonoma.edu:3333\r
Accept: text/html, text/plain, text/sgml, text/css, application/xhtml+xml, */*;q=0.01\r
Accept-Encoding: gzip, bzip2\r
Accept-Language: en\r
User-Agent: Lynx/2.8.9dev.4 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.0.1k-fips\r
" > test.in

echo -e "GET http://blue.cs.sonoma.edu:3333/page_name.html HTTP/1.0\r
Host: blue.cs.sonoma.edu:3333\r
Accept: text/html, text/plain, text/sgml, text/css, application/xhtml+xml, */*;q=0.01\r
Accept-Encoding: gzip, bzip2\r
Accept-Language: en\r
User-Agent: Lynx/2.8.9dev.4 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/1.0.1k-fips\r
" > test.ok

nc -l ${SERVER_PORT} > tmp.out &
./proxy ${PROXY_PORT} &
#nc localhost ${PROXY_PORT} < test.in
nc localhost ${PROXY_PORT} < test${TESTNO}.in

diff tmp.out test.ok

result=$?

# cleanup
# rm tmp.out
kill %1
kill %2

exit ${result}
